version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: north_by
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: north_by_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: north_by
      DB_PASSWORD: pass

volumes:
  db_data:
